import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  // 최상위 레이아웃
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>루트 레이아웃{children}</body>
    </html>
  );
}
// page컴포넌트가 children안으로 들어감, 레이아웃이 페이지를 포함하고있다.

// 로그인 유무에 따른 레이아웃이 다름
