// 기본적인 레이아웃 골격
"use client";
import Header from "@/components/Header/Header";
import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import { useEffect, useState } from "react";
// export const metadata: Metadata = {
//   title: "생활코딩",
//   description: "Generated by create next app",
// };

interface Topic {
  id: number;
  title: string;
  // Add any other properties present in your topic object
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [topics, setTopics] = useState<Topic[]>([]);
  useEffect(() => {
    fetch("http://localhost:9999/topics")
      .then((resp) => resp.json())
      .then((result) => {
        setTopics(result);
      });
  }, []);
  // 데이터를 가져오는데 시간이 걸림 , 비효율적, 자바스크립트를 끄면 , 서버와통신하는 서비스는 표현이 x -> 어떻게 해결할까
  console.log(topics);
  return (
    <html>
      <body>
        <Header />
        <ul>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ul>
        {children}
      </body>
    </html>
  );
}
